const imagesUser = [
  "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/astronaut_skull_in_cosmic_space.png",
  "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/astronaut_skull_in_space.png",
  "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/cloaked_figure_in_misty_city.png",
  "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/dog_survivor_in_ruined_city.png", 
  "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/spectral_astronaut_with_stellar_backdrop.png",
  "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/ghost_in_mirror.png",
  "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/astronaut_gazing_into_space.png",
  "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/cosmic_astronaut_with_vibrant_hues.png",
  "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/ominous_deep-sea_fish_lurking.png",
  "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/shattered_chains_and_skeleton_hands.png",
  "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/silhouette_in_abandoned_building.png",
  "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/soldier_walking_through_battlefield_aftermath.png",
  "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/samurai_dog_at_sunset_overlook.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/abandoned_room_with_webs.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/book_of_leaves_in_forest.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/boy_reading_in_abandoned_town.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/breaking_free_from_chains.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/child_in_overgrown_urban_landscape.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/child_looking_at_abandoned_playground.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/epic_battle_at_samurai_castle.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/explorer_in_abandoned_factory.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/figure_in_rain_at_cemetery.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/foggy_forest_not_found.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/forest_floor_with_hand.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/howling_wolf_under_moonlight.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/hyena_at_sunset_in_the_savanna.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/lion_and_hyenas_standoff.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/moonlit_seashore_with_dramatic_clouds.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/mysterious_fish_amidst_sea_forest.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/ominous_red_sky_explosion_over_ocean.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/overgrown_room_with_figure.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/poignant_ecological_narrative_with_beached_whale.png", //
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/salamander_by_moonlit_stream.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/salamander_on_mossy_forest_floor.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/samurai_cavalry_in_forest_light.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/samurai_dog_amidst_ruins.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/samurai_dogs_charging_across_bridge.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/samurai_dogs_marching_at_dawn.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/serene_nighttime_coastline.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/solitary_figure_on_rainy_park_bench.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/stormy_beach_with_seashells.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/tragic_scene_of_a_beached_whale.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/vibrant_salamander_in_forest_sunlight.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/warrior_dog_in_battlefield_aftermath.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/warrior_in_dusk_of_war-torn_land.png",
  // "https://generative-ai-ultisaer.s3.sa-east-1.amazonaws.com/images/wolf_howling_in_moonlit_forest.png"
]

const imagesBackgrounds = imagesUser.slice(0, 5)
const imagesIcons = imagesUser.slice(5, 14)
export { imagesBackgrounds, imagesIcons }